### ISSUE TITLE
The models do not match activity any more. 

### ISSUE THREAD

**Issue by sheiksadique** [gzuidhof/nn-transfer#14]
Keras.__version__ = 2.2.4
Tensorflow.__version__ = 1.11.0
PyTorch = 1.0.0a0+ff608a9

I tried running the example and the activity does not match. Any ideas?

**Comment by Owen-Liuyuxuan** [comment]
I find the same problem
![screenshot from 2018-12-25 22-43-34](https://user-images.githubusercontent.com/31618608/50423885-96d26c00-0896-11e9-9e81-0652dc71c993.png)

**Comment by gzuidhof** [comment]
That's a shame, I guess things don't stay the same and an update is needed.

I added a note in the README to warn users of this.
