### ISSUE TITLE
Seg fault on AWS Deep learning AMI

### ISSUE THREAD

**Issue by dathath** [gzuidhof/nn-transfer#4]
I'm trying to use this on the AWS Deep learning AMI instance, and it segfaults when I run 
'from nn_transfer import transfer'. 

It works perfectly fine on my laptop. Any help would be really appreciated!

**Comment by dathath** [comment]
Strangely, changing the order of imports in transfer.py fixes it
The new functional order:

import keras
import numpy as np
import h5py
import torch

**Comment by gzuidhof** [comment]
Hey Dathath, thanks for creating the issue!

It seems they are aware of the problem: https://github.com/pytorch/pytorch/issues/3059. 

The easy fix for now of course is to swap around the import of keras and pytorch, which I have just done :) Thanks again!
