### ISSUE TITLE
mapping multi layer LSTM

### ISSUE THREAD

**Issue by rgsachin** [gzuidhof/nn-transfer#5]
Hi Gudio,
Nice framework you have built.
I've a pretrained pytorch, which 2 layer bidirectional lstm
`nn.LSTM(300, 300, num_layers=2, bidirectional=True)`
`print(util.state_dict_layer_names(state_dict))`
prints
['rnn']
Unlike pytorch Keras layers have to be defined separately, like below
`model = Sequential()
model.add(Bidirectional(LSTM(300, return_sequences=True),input_shape=(300,10),name='rnn'))
model.add(Bidirectional(LSTM(300)))`
How do I map 1 name in pytorch to 2 layers in Keras. ?
Thanks in advance

**Comment by gzuidhof** [comment]
Hi rgsachin,

It is not possible, there is currently no explicit support for RNNs. I am also not planning on creating support for this anytime soon (PRs are welcome though), sorry.
